project_name: engarde 

before:
  hooks:
    - go mod tidy

builds:
- main: ./main.go

  env:
    - CGO_ENABLED=0
    
  goos:
    - darwin
    - linux
    - freebsd
    - windows

  goarch:
    - 386
    - amd64
    - arm
    - arm64
 
  ignore:
      - goos: freebsd
        goarch: arm64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: zip
brews:
-
  github:
    owner: kushthedude 
    name: homebrew-engarde
  homepage: https://github.com/kushthedude/engarde
  
  commit_author:
    name: kushthedude
    email: kushthedude@gmail.com

  folder: Formula

  description: "Engarde - Stay on guard with Envoy Access Logs"

  skip_upload: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc

release:
  name_template: "Engarde {{.Tag}}"
